# Generated by Django 5.1.7 on 2026-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.TextField()),
                ('business_problem', models.TextField()),
                ('tools_used', models.CharField(max_length=255)),
                ('key_features', models.TextField()),
                ('role_contribution', models.TextField()),
                ('biggest_challenge', models.TextField()),
                ('lessons_learned', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('automation', 'Automation'), ('agent', 'Agent'), ('media', 'Media'), ('machine-learning', 'Machine Learning'), ('web-app', 'Web App')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
